wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.8
    start_time: 1638470271
    t:
      1:
      - 1
      - 5
      4: 3.8.8
      5: 0.12.7
      8:
      - 1
      - 2
      - 5
